import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Nav } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Roboto } from 'next/font/google'
import Footer from "./testing/Footer";

const inter = Roboto({
  subsets: ['latin'],
  weight: "400"
})
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <Nav />
          {children}
          <div className="w-full bg-white dark:bg-black">
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
